import React from 'react';
import { Header } from '../sections/Header';
import { Footer } from '../sections/Footer';
import '../styles/terms-of-service.css';

export function TermsOfService(): React.ReactElement {
  return (
    <div className="terms-of-service-page">
      <Header />
      <main className="terms-of-service-main">
        <div className="container">
          <div className="terms-of-service-content">
            <h1 className="terms-of-service-title">Terms of Service</h1>
            <p className="terms-of-service-updated">Last updated: April 15, 2025</p>
            <hr className="terms-of-service-divider" />
            
            <section className="terms-intro">
              <p>
                By accessing and using the site, you agree to these terms of use. Please read these conditions 
                carefully before using the Skysecure website. By using the Skysecure.com website, you signify your 
                agreement to be bound by these conditions. These "Conditions of Use" constitute an electronic 
                record within the meaning of the applicable law. This electronic record is generated by a computer 
                system and does not require any physical or digital signatures.
              </p>
            </section>

            <section className="terms-section">
              <h2>1. Definitions</h2>
              
              <p>
                <strong>Consumer</strong> means an individual acting for purposes which are wholly or mainly outside that 
                individual's trade, business, craft or profession.
              </p>
              
              <p>
                <strong>Skysecure's</strong> means Skysecure Technologies Private Limited also referred to as "we" or "us" in these 
                terms and conditions.
              </p>
              
              <p>
                <strong>Business Customer</strong> means a customer who is not a consumer.
              </p>
            </section>

            <section className="terms-section">
              <h2>2. Website Conditions of Use</h2>
              
              <p>
                Your use of this site, which is provided by Skysecure, by using this site you signify your consent to 
                be bound by these terms and conditions.
              </p>
              
              <p>
                If you do not agree with any part of the following terms and conditions you must not use this site. 
                Some areas of the site require registration.
              </p>
              
              <p>
                You agree, understand and acknowledge that the website is an online platform that enables you to 
                purchase products listed on the website at the price indicated therein at any time from any location 
                within the jurisdiction as set forth below.
              </p>
              
              <p>
                By completing the initial registration form and by entering your email address and password, you will 
                be deemed to have accepted these terms and conditions. Also, by subscribing to any of our email 
                services, you are deemed to have accepted these terms and conditions. If you register with this site, 
                you should read and adhere to our privacy policy.
              </p>
              
              <p>
                The right to use this website does not include any resale or commercial use of this website or its 
                contents; any collection and use of any product listings, descriptions, or prices; any derivative use of 
                this website or its contents; any downloading or copying of account information for the benefit of 
                another seller; or any use of data mining, robots, or similar data gathering and extraction tools.
              </p>
              
              <div className="terms-prohibited">
                <h3>You must not use any Skysecure services:</h3>
                <p>
                  In any way that causes, or is likely to cause, Skysecure, or any access to it to be interrupted, 
                  damaged or impaired in any way, or
                </p>
                <p>
                  For fraudulent purposes, or in connection with a criminal offence or other unlawful activity, or
                </p>
                <p>
                  Threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with 
                  foreign states, or public order or causes incitement to the commission of any cognizable offence 
                  or prevents investigation of any offence or is insulting any other nation.
                </p>
              </div>
              
              <p>
                We reserve the right to refuse service, terminate accounts or remove or edit content if you are in 
                breach of applicable laws, these Conditions of Use or any other applicable terms and conditions, 
                guidelines or policies.
              </p>
              
              <p>
                You are advised to check the terms of use from time to time for any updates or changes. If you do 
                not accept such amendments, you must cease using this site.
              </p>
            </section>

            <section className="terms-section">
              <h2>3. Trademarks and Copyright</h2>
              
              <p>
                Trade names and marks (other than Skysecure's) are not always indications of the actual 
                manufacturer of a particular product and may rather be indicative of general use systems and 
                machines associated with such products.
              </p>
              
              <p>
                You must not reproduce any part of this website or the material or transmit it to or store it in any other 
                website or disseminate any part of the material in any other form unless we have indicated in writing 
                that you may do so. The design, arrangement and look and feel of this website are also the copyright 
                of Skysecure and/or its licensors and may not be copied or otherwise reproduced.
              </p>
              
              <p>
                The 'Skysecure' is a registered trademark under the Indian Trade Marks Act, 1999, and any use of 
                the same without the consent shall be liable to be punished under the act.
              </p>
              
              <p>
                In the case of component purchases, Customers requiring a particular brand of product should, 
                before placing an order, check with Skysecure the identity of the manufacturer of component it is 
                proposed to purchase.
              </p>
              
              <p>
                Skysecure respects the intellectual property of others. If you believe that your intellectual property 
                rights have been used in a way that gives rise to concerns of infringement, please inform about the 
                same through the following email address <a href="mailto:support@skysecure.ai" className="terms-link">support@skysecure.ai</a>
              </p>
            </section>

            <section className="terms-section">
              <h2>4. Registration</h2>
              
              <p>Access to the registration area on this site is permitted on the basis that:</p>
              
              <p>
                Your Email Id and password are personal to you and may not be used by anyone else to access 
                this site;
              </p>
              
              <p>
                You will not do anything which would assist anyone who is not a registered user to gain access 
                to any registration area of this site;
              </p>
              
              <p>
                You do not create additional registration accounts to abuse the functionality of the site, or other 
                users; nor do you seek to pass yourself off as another user.
              </p>
              
              <p>
                It is your responsibility to maintain the confidentiality of your password and you are responsible for 
                all activity that occurs under your user name and password. We will not be liable where your 
                password is used by someone else.
              </p>
              
              <p>
                We reserve the right to cancel your account(s) and to ban you from registering a new account if you 
                are found using duplicate accounts or the security of your account is compromised in any way and 
                for any reason.
              </p>
              
              <p>
                Any questions about these terms and conditions or reports of anyone abusing the website or otherwise 
                not complying with these terms and conditions should be addressed to <a href="mailto:support@Skysecure.ai" className="terms-link">support@Skysecure.ai</a>
              </p>
            </section>

            <section className="terms-section">
              <h2>5. Interest-based Ads</h2>
              
              <p>
                Interest-based ads are sometimes referred to as personalised or targeted ads. We show interest-based ads to display features, products, and services that might be of interest to you.
              </p>
              
              <p>
                To serve you interest-based ads, we use information such as your interactions with Skysecure sites, 
                content, or services. In serving you interest-based ads we only keep information collected for as long 
                as required to provide our advertising services, in accordance with our Privacy policy and applicable 
                laws.
              </p>
              
              <p>
                We work with third parties, such as advertisers, publishers, social media networks, search engines, 
                ad serving companies, and advertising companies working on their behalf, to improve the relevance 
                of ads we serve.
              </p>
              
              <p>
                Third-party advertisers or advertising companies working on their behalf sometimes use cookies in 
                the process of delivering content, including ads, directly to your browser or device, and they may 
                automatically receive an IP address when this happens. They may also use cookies to measure the 
                effectiveness of their ads, show you more relevant advertising content, and perform services on 
                behalf of Skysecure. For information on how to control and delete cookies please visit our cookies 
                policy.
              </p>
              
              <p>
                Skysecure offers you choices about receiving interest-based ads from us. You can choose not to 
                receive interest-based ads from Skysecure. You may still see ads, but they may not be based on your 
                interests. For opting out of interest-based ads please see our cookies policy.
              </p>
            </section>

            <section className="terms-section">
              <h2>6. Links to Other Websites</h2>
              
              <p>
                This site may contain links to third-party websites ("other sites") that are not under Skysecure's 
                control.
              </p>
              
              <p>
                Skysecure makes no claim or responsibility regarding the quality, nature and reliability of the other 
                sites that are accessible by hyperlinks from the sites or link to the sites.
              </p>
              
              <p>
                Skysecure provides these links to you as a convenience and inclusion of any link does not imply 
                endorsement by Skysecure as of other sites or any association with operators of such other site.
              </p>
              
              <p>
                You are responsible for viewing and abiding by the privacy statements and terms of use posted at 
                any third-party sites.
              </p>
            </section>

            <section className="terms-section">
              <h2>7. Viruses, Malware, and Security</h2>
              
              <p>
                Skysecure uses technical and organisational security measures to protect the personal information 
                supplied by you against loss, destruction, and any unauthorised access by third parties.
              </p>
              
              <p>
                We work to protect the security of your information during transmission by using Secure Sockets 
                Layer (SSL) software, which encrypts information you input.
              </p>
              
              <p>
                We follow the Payment Card Industry Data Security Standard (PCI DSS) when handling Debit and 
                Credit card data.
              </p>
            </section>

            <section className="terms-section">
              <h2>8. Errors and Omissions</h2>
              
              <p>
                We do our best to ensure that information on our website is complete, accurate and current.
              </p>
              
              <p>
                Despite our efforts, the information our website be occasionally inaccurate or out of date. All 
                specifications, products, description and prices of products on the site are subject to change.
              </p>
              
              <p>
                The inclusion of any products or services on our website at a particular time does not imply
              </p>
            </section>

            <div className="terms-contact">
              <h3>Questions or Concerns?</h3>
              <p>
                If you have any questions about these Terms of Use or need clarification on any point, 
                please don't hesitate to contact us.
              </p>
              <p>
                <a href="mailto:support@skysecure.ai" className="terms-link">support@skysecure.ai</a>
              </p>
            </div>

            <hr className="terms-copyright-divider" />
            
            <div className="terms-copyright">
              <p>© 2025 SkySecure Technologies, Inc.</p>
              <p>All Rights Reserved</p>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}

